[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AT3oNZ9od5UCODED29dw-HM1k0KMlUH59_rpG6Rg_oxu2v6UyHKkzJpojZN8jYsmiWhmVvnRi68yfX4UR824FkOmSjfDW_BYFLadT6-B84Gxv19Gk-pa8Ms-WxahW7eLVp92wd8zBRyviLLVfm2Hc_erhH0duY5EENolzukukmxvJuYHtEk9vbtu2oYxtKAZxntDXckaCgYKAbMSARMSFQHGX2Misc3RYyTBx1-yGX-dAzOU2A0206","token_type":"Bearer","refresh_token":"1//0gQrEst_WhfcvCgYIARAAGBASNwF-L9IrMWQLi8NCZyZvKh1czAkPPV9Zb6LylOfNSRS9SGafLlFHGLnEK47c85Oth_7yaH10yqs","expiry":"2026-06-21T20:57:10.4221271+07:00","expires_in":3599}
